#ifndef CLASECUADRICULAV1_GLOBAL_H
#define CLASECUADRICULAV1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLASECUADRICULAV1_LIBRARY)
#  define CLASECUADRICULAV1SHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLASECUADRICULAV1SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLASECUADRICULAV1_GLOBAL_H
